### ISSUE TITLE
docs: remove commented path from the the $SHELL line reported at the end of prompt install

### ISSUE THREAD

**Issue by dmccaffery** [automotiveMastermind/prompt#64]
<img width="592" alt="image" src="https://user-images.githubusercontent.com/1803684/99755206-15b39c00-2ae2-11eb-84ef-ce5c74ae7ed3.png">

If someone copies the entire command (including the comment containing the expected shell path), then an error will be reported.

We should remove (or move) the path as its unclear whether or not that should be copied.

**Comment by dmccaffery** [comment]
https://github.com/automotiveMastermind/prompt/blob/275f62c769f346e7b9acdba3cd18eb58bdf2f23f/src/sh/scripts/use-shell#L51

**Comment by patrickserrano** [comment]
Oh man I've seen people do this. Would it make sense to do something like:
```sh
echo "${CLR_BRIGHT_BLUE}"
echo "\$SHELL set to: $SHELL"
echo "${CLR_CLEAR}"
echo "${CLR_SUCCESS}"
echo "##############################################################################"
echo "##############################################################################"
echo "     PLEASE RUN: exec -l \$SHELL"
echo "##############################################################################"
echo "##############################################################################"
echo "${CLR_CLEAR}"
```

That way it's clear what the value of `$SHELL` is and it's out of the comment asking the user to take action. 

I don't know that it makes sense to remove printing `$SHELL` because depending on how prompt was installed a user could end up changing their default shell.
